import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import questionsData from"../../test-data/QUESTIONS-MVP.json";import goalsData from"../../test-data/LEARNING-GOALS-MVP.json";import{startExercise,reduceExercise,type ExerciseAttempt}from"../exercises/exercise-adapter";import{createSession,reduceSession,type SessionState}from"../learning-engine/session-state";import{nextSessionState}from"../learning-engine/session-loop";import type{LearningEvent,LearningGoalRelation}from"../domain/types";import{toExerciseViewModel}from"../ui/exercise-view-model";import"../ui/mees.css";
const questions=questionsData.questions as any[];const relations=goalsData.relations as LearningGoalRelation[];const deps={questions,relations};const SESSION="demo-session";
function plan(s:SessionState){return nextSessionState(s,deps)}
function App(){const initial=useMemo(()=>plan(createSession(SESSION,"LG-TEST-007")),[]);const[session,setSession]=useState(initial.state);const[exercise,setExercise]=useState<ExerciseAttempt>(()=>startExercise(initial.plan!.question as any));const[input,setInput]=useState("");const[finished,setFinished]=useState(false);const vm=toExerciseViewModel(exercise,{current:Math.min(session.meaningfulBlocks+1,5),total:5});
const hint=()=>setExercise(x=>reduceExercise(x,{type:"hint"}));
const advance=()=>{let s=reduceSession(session,{type:"complete_block"});const r=plan(s);setSession(r.state);setInput("");if(!r.plan||r.state.status==="ended"||!r.plan.question){setFinished(true);return}setExercise(startExercise(r.plan.question as any))};
const submit=()=>{if(exercise.attempt.uiState==="completed"){advance();return}const before=exercise;const after=before.kind==="basic"?reduceExercise(before,{type:"submit_text",value:input}):reduceExercise(before,{type:"submit"});setExercise(after);if(after.attempt.submissions===before.attempt.submissions)return;const correct=after.attempt.uiState==="completed";const q=after.attempt.question;const event:LearningEvent={id:"E-"+Date.now(),goalId:q.goal,questionId:q.id,questionFamily:q.family,sessionId:SESSION,occurredAt:new Date().toISOString(),type:"answer_submitted",outcome:correct?"correct":"incorrect",support:after.attempt.hintIndex>=0?"light_support":"independent",representation:q.type,validity:"valid",source:"digital"};setSession(s=>reduceSession(s,{type:"record_event",event}))};
if(finished)return <main className="mees-shell"><header className="mees-header"><span className="mees-wordmark">Mees</span></header><section className="mees-card mees-finish"><p className="mees-eyebrow">Voor nu klaar</p><h1>Mooi gewerkt.</h1><p>Mees heeft genoeg gezien voor deze korte testsessie. Later bewaren we dit veilig in je profiel.</p><button className="mees-primary" onClick={()=>location.reload()}>Nog een keer</button></section></main>;
return <main className="mees-shell"><header className="mees-header"><span className="mees-wordmark">Mees</span><span className="mees-progress">{vm.progressLabel}</span><button className="mees-stop" onClick={()=>setFinished(true)}>Stoppen</button></header><section className="mees-card"><p className="mees-eyebrow">Rekenen · voor jou</p><h1>{vm.prompt}</h1>{exercise.kind==="basic"?<div className="basic-answer"><label htmlFor="answer">Jouw antwoord</label><input id="answer" inputMode="numeric" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submit()}} autoFocus/><span>Typ je antwoord en kies Controleren.</span></div>:<NumberLine exercise={exercise} setExercise={setExercise}/>}<div className="mees-actions"><button className="mees-primary" onClick={submit}>{vm.primaryLabel}</button>{vm.canAskHint&&<button className="mees-secondary" onClick={hint}>Hint</button>}</div>{vm.hint&&<aside className="mees-hint"><strong>Een zetje</strong><p>{vm.hint}</p></aside>}{vm.feedback&&<p className="mees-feedback" role="status">{vm.feedback}</p>}</section></main>}
function NumberLine({exercise,setExercise}:{exercise:Extract<ExerciseAttempt,{kind:"number_line"}>;setExercise:React.Dispatch<React.SetStateAction<ExerciseAttempt>>}){const a=exercise.attempt,p=a.question.params,step=p.minor_step??1,current=a.selectedValue??p.start??p.min;const move=(d:number)=>setExercise(x=>reduceExercise(x,{type:"select_value",value:current+d}));const major=p.major_step??10;const ticks=[];for(let n=p.min;n<=p.max;n+=major)ticks.push(n);return <div className="number-line"><div className="number-line-track">{ticks.map(n=><span className="tick" key={n}>{n}</span>)}</div><p className="number-line-current">Huidige positie: <strong>{current}</strong></p><div className="number-line-controls"><button onClick={()=>move(-step)} aria-label="Eén stap terug">−</button><button onClick={()=>move(step)} aria-label="Eén stap vooruit">+</button></div></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
