import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import questionsData from"../../test-data/QUESTIONS-MVP.json";import goalsData from"../../test-data/LEARNING-GOALS-MVP.json";import{startExercise,reduceExercise,type ExerciseAttempt}from"../exercises/exercise-adapter";import{createSession,reduceSession,type SessionState}from"../learning-engine/session-state";import{nextSessionState,returnFromPrerequisite}from"../learning-engine/session-loop";import type{LearningEvent,LearningGoalRelation}from"../domain/types";import{toExerciseViewModel}from"../ui/exercise-view-model";import{ageBandClass,ageBandForGroup}from"../ui/age-profile";import HomeV2 from "./HomeV2";import"../ui/mees.css";
const questions=questionsData.questions as any[];const relations=goalsData.relations as LearningGoalRelation[];const deps={questions,relations};const SESSION="demo-session";function plan(s:SessionState){return nextSessionState(s,deps)}
type Screen="home"|"session"|"done";type EndReason="completed"|"stopped"|"needs_help";function App(){const[screen,setScreen]=useState<Screen>("home");const[endReason,setEndReason]=useState<EndReason>("completed");const[group,setGroup]=useState(5);const ageBand=ageBandForGroup(group);const ageClass=ageBandClass(ageBand);const initial=useMemo(()=>plan(createSession(SESSION,"LG-TEST-007")),[]);const[session,setSession]=useState(initial.state);const[exercise,setExercise]=useState<ExerciseAttempt>(()=>startExercise(initial.plan!.question as any));const[input,setInput]=useState("");const vm=toExerciseViewModel(exercise,{current:Math.min(session.meaningfulBlocks+1,5),total:5});
const stop=()=>{setEndReason("stopped");setSession(s=>reduceSession(s,{type:"record_intervention",intervention:{id:"I-S-"+Date.now(),goalId:s.activeGoalId,sessionId:SESSION,occurredAt:new Date().toISOString(),type:"session_stopped"}}));setScreen("done")};const reset=()=>{setEndReason("completed");const r=plan(createSession(SESSION,"LG-TEST-007"));setSession(r.state);setExercise(startExercise(r.plan!.question as any));setInput("");setScreen("session")};const hint=()=>{setExercise(x=>reduceExercise(x,{type:"hint"}));setSession(s=>reduceSession(s,{type:"record_intervention",intervention:{id:"I-H-"+Date.now(),goalId:s.activeGoalId,sessionId:SESSION,occurredAt:new Date().toISOString(),type:exercise.attempt.hintIndex<0?"light_hint":"strong_hint"}}))};const completed=exercise.attempt.uiState==="completed";const isRetry=exercise.attempt.uiState==="incorrect_can_retry";const canSubmit=exercise.kind==="basic"?Boolean(input.trim()):exercise.attempt.selectedValue!==undefined;const advance=()=>{let s=reduceSession(session,{type:"complete_block"});if(s.goalStack.length>0&&s.events.filter(e=>e.goalId===s.activeGoalId&&e.type==="answer_submitted").some(e=>e.outcome==="correct"))s=returnFromPrerequisite(s);const r=plan(s);setSession(r.state);setInput("");if(!r.plan||r.state.status==="ended"||!r.plan.question){setEndReason(r.plan?.action.type==="propose_tutor_help"?"needs_help":"completed");setScreen("done");return}setExercise(startExercise(r.plan.question as any))};
const submit=()=>{if(exercise.attempt.uiState==="completed"){advance();return}const before=exercise;const after=before.kind==="basic"?reduceExercise(before,{type:"submit_text",value:input}):reduceExercise(before,{type:"submit"});setExercise(after);if(after.attempt.submissions===before.attempt.submissions)return;const q=after.attempt.question;const event:LearningEvent={id:"E-"+Date.now(),goalId:q.goal,questionId:q.id,questionFamily:q.family,sessionId:SESSION,occurredAt:new Date().toISOString(),type:"answer_submitted",outcome:after.attempt.uiState==="completed"?"correct":"incorrect",support:after.attempt.hintIndex>=0?"light_support":"independent",representation:q.type,validity:"valid",source:"digital"};setSession(s=>reduceSession(s,{type:"record_event",event}))};
const sessionStopped=endReason==="stopped";const sessionNeedsHelp=endReason==="needs_help";const homeV2Review=new URLSearchParams(window.location.search).get("homev2")==="1";if(homeV2Review&&screen==="home")return <HomeV2 onStart={reset}/>;if(screen==="home")return <main className={"mees-shell mees-home-shell "+ageClass}>
<header className="mees-header mees-home-header">
  <Brand/>
  <nav className="mees-home-nav" aria-label="Hoofdnavigatie">
    <button className="is-active" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>Home</button>
    <button onClick={()=>document.getElementById("subjects-title")?.scrollIntoView({behavior:"smooth"})}>Leren</button>
    <button onClick={()=>document.getElementById("discovery-title")?.scrollIntoView({behavior:"smooth"})}>Ontdekboek</button>
  </nav>
  <label className="mees-group-switcher">Groep
    <select value={group} onChange={e=>setGroup(Number(e.target.value))} aria-label="Kies groep voor voorbeeld">
      {[3,4,5,6,7,8].map(g=><option key={g} value={g}>{g}</option>)}
    </select>
  </label>
</header>
<section className="mees-home">
  <section className="mees-home-hero">
    <img className="mees-home-hero-scene" src={ageBand==="junior"?"/assets/mees/MEES-SCENE-FOREST-DISCOVERY-001.jpg":"/assets/mees/MEES-SCENE-MOUNTAIN-LAKE-001.jpg"} alt="" aria-hidden="true"/>
    <div className="mees-home-hero-overlay" aria-hidden="true"/>
    <div className="mees-home-hero-copy">
      <p className="mees-eyebrow">{ageBand==="junior"?"Hoi Emma!":ageBand==="middle"?"Goedemorgen Emma!":"Goedemorgen Emma."}</p>
      <h1>{ageBand==="junior"?"Zullen we samen iets nieuws ontdekken?":ageBand==="middle"?"Wat ga je vandaag ontdekken?":"Waar wil je vandaag verder mee?"}</h1>
      <p>{ageBand==="junior"?"Kies iets dat je leuk vindt. Mees helpt je onderweg.":ageBand==="middle"?"Je kunt verder waar je was of zelf een onderwerp kiezen.":"Ga verder met je leerroute of kies een onderwerp om te verdiepen."}</p>
    </div>
    <div className="mees-home-hero-mascot" aria-hidden="true">
      <img src="/assets/mees/v2/mascot/MEES-V2-MASCOT-BACKPACK-001.svg" alt=""/>
    </div>
  </section>

  <section className="mees-home-section" aria-labelledby="subjects-title">
    <div className="mees-section-heading"><div><p className="mees-eyebrow">Jouw vakken</p><h2 id="subjects-title">Kies een onderwerp</h2></div></div>
    <div className="mees-subject-grid">
      <button className="mees-subject-card subject-math" onClick={reset}><img className="mees-subject-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-MATH-001.svg" alt="" aria-hidden="true"/><span className="mees-subject-copy"><strong>Rekenen</strong><small>{ageBand==="senior"?"Verdiep en oefen":"Getallen, sommen en meer"}</small></span><span className="mees-subject-arrow" aria-hidden="true">→</span></button>
      <article className="mees-subject-card subject-language is-coming-soon"><img className="mees-subject-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-READING-001.svg" alt="" aria-hidden="true"/><span className="mees-subject-copy"><strong>Taal & lezen</strong><small>{ageBand==="senior"?"Analyseer en groei":"Woorden en verhalen"}</small><span className="mees-coming-soon">Binnenkort</span></span></article>
      <article className="mees-subject-card subject-world is-coming-soon"><img className="mees-subject-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-NATURE-001.svg" alt="" aria-hidden="true"/><span className="mees-subject-copy"><strong>Wereld & natuur</strong><small>{ageBand==="senior"?"Onderzoek en begrijp":"Ontdek de wereld"}</small><span className="mees-coming-soon">Binnenkort</span></span></article>
      <article className="mees-subject-card subject-creative is-coming-soon"><img className="mees-subject-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-CREATIVE-001.svg" alt="" aria-hidden="true"/><span className="mees-subject-copy"><strong>Creatief</strong><small>{ageBand==="senior"?"Ontwerp en maak":"Teken, maak en ontdek"}</small><span className="mees-coming-soon">Binnenkort</span></span></article>
    </div>
  </section>

  <section className="mees-home-dashboard">
    <div className="mees-home-panel">
      <div className="mees-section-heading"><div><p className="mees-eyebrow">Verder leren</p><h2>{ageBand==="senior"?"Jouw volgende uitdaging":"Vandaag voor jou"}</h2></div></div>
      <div className="mees-learning-cards">
        <button className="mees-learning-card" onClick={reset}><img className="mees-learning-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-MATH-001.svg" alt="" aria-hidden="true"/><span><strong>{ageBand==="senior"?"Procenten berekenen":"Verder met rekenen"}</strong><small>Rekenen</small></span><span aria-hidden="true">→</span></button>
        <article className="mees-learning-card is-muted"><img className="mees-learning-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-READING-001.svg" alt="" aria-hidden="true"/><span><strong>{ageBand==="junior"?"Een kort verhaaltje":"Een tekst om te ontdekken"}</strong><small>Taal & lezen</small></span></article>
        {ageBand!=="junior"&&<article className="mees-learning-card is-muted"><img className="mees-learning-image" src="/assets/mees/v2/subjects/MEES-V2-SUBJECT-NATURE-001.svg" alt="" aria-hidden="true"/><span><strong>{ageBand==="senior"?"Energie en klimaat":"Leven in het water"}</strong><small>Wereld & natuur</small></span></article>}
      </div>
    </div>

    <aside className="mees-home-panel mees-home-status">
      <p className="mees-eyebrow">Ga verder waar je was</p>
      <h2>Je leerroute staat voor je klaar.</h2>
      <p>Mees onthoudt welke stap je geoefend hebt en kiest daarna iets dat daarbij past.</p>
      <button className="mees-button mees-button--primary" onClick={reset}>Verder met rekenen</button>
    </aside>
  </section>

  <section className="mees-discovery-book" aria-labelledby="discovery-title">
    <div className="mees-discovery-copy">
      <p className="mees-eyebrow">Ontdekboek</p>
      <h2 id="discovery-title">Iets geleerd? Neem een weetje mee.</h2>
      <p>Na een leerroute kan er een passend weetje in je Ontdekboek verschijnen. Geen punten of prijzen, gewoon interessante dingen om later terug te lezen.</p>
      <button className="mees-button mees-button--secondary">Bekijk het Ontdekboek</button>
    </div>
    <article className="mees-fact-card">
      <span className="mees-fact-label">Wist je dat?</span>
      <strong>{ageBand==="junior"?"Een octopus drie harten heeft?":ageBand==="middle"?"Bijen met een dans aan elkaar kunnen laten zien waar bloemen staan?":"Licht van de zon er ongeveer acht minuten over doet om de aarde te bereiken?"}</strong>
      <p>{ageBand==="senior"?"Een kort weetje kan een startpunt zijn voor verder onderzoek.":"Je kunt zulke weetjes bewaren en later opnieuw bekijken."}</p>
    </article>
  </section>
</section></main>;if(screen==="done")return <main className={"mees-shell mees-done "+ageClass}><header className="mees-header mees-done-header"><Brand/></header><section className="mees-card mees-finish"><img className="mees-finish-mascot" src="/assets/mees/MEES-BRAND-HEAD-001.png" alt="" aria-hidden="true"/><p className="mees-eyebrow">{sessionStopped?"Voor nu gestopt":sessionNeedsHelp?"Even samen kijken":"Voor vandaag klaar"}</p><h1>{sessionStopped?"Prima, je kunt hier stoppen.":sessionNeedsHelp?"Dit stukje vraagt om extra uitleg.":"Mooi gewerkt."}</h1><p>{sessionStopped?"Je hoeft niet alles in één keer af te maken. Je kunt straks of een andere keer verder.":sessionNeedsHelp?"Vraag een ouder of leerkracht om even mee te kijken. Daarna kun je weer verder.":"Je hebt geoefend en verschillende stappen geprobeerd. Dat is genoeg voor nu."}</p><div className="mees-finish-actions"><button className="mees-button mees-button--primary" onClick={()=>setScreen("home")}>Naar home</button>{sessionStopped&&<button className="mees-button mees-button--secondary" onClick={()=>setScreen("session")}>Toch verder</button>}</div></section><p className="mees-finish-note">Je hoeft niets bij te houden. Mees helpt je de volgende keer weer verder.</p></main>;
return <main className={"mees-shell mees-focus-mode "+ageClass}><header className="mees-session-header"><Brand/><span className="mees-progress">{vm.progressLabel}</span><button className="mees-button mees-button--quiet mees-stop" onClick={stop}>Stoppen</button></header><div className="mees-focus-shell">{session.goalStack.length>0&&<div className="route-note" role="status"><span className="route-note-icon" aria-hidden="true">↙</span><div><strong>Even terug naar de basis</strong><span>We bekijken eerst een kleinere stap. Daarna ga je vanzelf verder waar je was.</span></div></div>}<section className={"mees-card mees-exercise-card state-"+exercise.attempt.uiState}><div className="mees-exercise-intro"><div><p className="mees-eyebrow">Rekenen</p><span className="mees-exercise-kicker">Neem rustig de tijd.</span></div></div><h1>{vm.prompt}</h1>{exercise.kind==="basic"?<div className="basic-answer"><label htmlFor="answer">Jouw antwoord</label><input id="answer" inputMode="numeric" value={input} disabled={completed} onChange={e=>{setInput(e.target.value);if(exercise.attempt.uiState==="incorrect_can_retry")setExercise(x=>({...x,attempt:{...x.attempt,uiState:"answering"}} as ExerciseAttempt))}} onKeyDown={e=>{if(e.key==="Enter")submit()}} aria-describedby="answer-help"/><span id="answer-help">{isRetry?"Je kunt je antwoord aanpassen.":"Vul je antwoord in."}</span></div>:<NumberLine exercise={exercise} setExercise={setExercise}/>}<div className="mees-actions"><button className="mees-button mees-button--primary" onClick={submit} disabled={!completed&&!canSubmit}>{vm.primaryLabel}</button>{vm.canAskHint&&<button className="mees-button mees-button--secondary" onClick={hint}>{vm.hint?"Nog een hint":"Hint"}</button>}</div>{vm.hint&&<aside className="mees-feedback mees-feedback--hint"><span className="mees-feedback-icon" aria-hidden="true">?</span><div><strong>Een zetje</strong><p>{vm.hint}</p></div></aside>}{vm.feedback&&<div className={"mees-feedback "+(exercise.attempt.uiState==="completed"?"mees-feedback--success":"mees-feedback--retry")} role="status"><span className="mees-feedback-icon" aria-hidden="true">{exercise.attempt.uiState==="completed"?"✓":"↻"}</span><div><strong>{exercise.attempt.uiState==="completed"?"Goed bezig!":"Probeer nog eens"}</strong><p>{vm.feedback}</p>{exercise.attempt.uiState==="completed"&&exercise.attempt.question.explanation&&<div className="mees-mini-explanation"><span>Zo kun je het zien</span><p>{exercise.attempt.question.explanation}</p></div>}{exercise.attempt.uiState==="completed"&&session.goalStack.length>0&&<p className="mees-return-note">Hierna ga je terug naar de som waar je mee bezig was.</p>}</div></div>}</section></div></main>}
function Brand(){return <span className="brand" aria-label="Mees"><img className="mees-brand-lockup" src="/assets/mees/v2/brand/MEES-V2-BRAND-LOGO-HORIZONTAL-001.svg" alt="" aria-hidden="true"/></span>}function NumberLine({exercise,setExercise}:{exercise:Extract<ExerciseAttempt,{kind:"number_line"}>;setExercise:React.Dispatch<React.SetStateAction<ExerciseAttempt>>}){const a=exercise.attempt,p=a.question.params,step=p.minor_step??1,current=a.selectedValue??p.start??p.min;const clamp=(n:number)=>Math.max(p.min,Math.min(p.max,n));const locked=a.uiState==="completed";const move=(d:number)=>{if(locked)return;setExercise(x=>reduceExercise(x,{type:"select_value",value:clamp(current+d)}))};const pct=(n:number)=>((n-p.min)/(p.max-p.min))*100;const major=p.major_step??(p.max-p.min<=20?5:10);const ticks:number[]=[];for(let n=p.min;n<=p.max;n+=major)ticks.push(n);if(ticks.at(-1)!==p.max)ticks.push(p.max);return <div className="number-line"><div className="number-line-viewport" aria-label={"Getallenlijn van "+p.min+" tot "+p.max}><div className="number-line-rail">{ticks.map(n=><React.Fragment key={n}><span className="number-line-tick" style={{left:pct(n)+"%"}}/><span className="number-line-label" style={{left:pct(n)+"%"}}>{n}</span></React.Fragment>)}{p.start!==undefined&&<span className="number-line-start" title={"Start "+p.start} style={{left:pct(p.start)+"%"}}/>}<span className="number-line-marker" style={{left:pct(current)+"%"}}><span>{current}</span></span></div></div><p className="number-line-current">{p.start!==undefined?<>Start bij <strong>{p.start}</strong>. Kies waar je uitkomt.</>:<>Kies het juiste getal.</>}</p><div className="number-line-controls" aria-label="Verplaats het getal"><button onClick={()=>move(-10)} className="jump-ten" disabled={locked||current<=p.min}>−10</button><button onClick={()=>move(-step)} disabled={locked||current<=p.min}>−{step}</button><button onClick={()=>move(step)} disabled={locked||current>=p.max}>+{step}</button><button onClick={()=>move(10)} className="jump-ten" disabled={locked||current>=p.max}>+10</button></div><p className="number-line-help">Gebruik de knoppen om het blauwe punt te verplaatsen.</p></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);